# Generated by Django 4.0.6 on 2022-07-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
    ]
